config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [ :show, :edit, :update ]

  resources :courses do
    resources :lessons
  end

  resources :enrollments, only: [ :create, :destroy ]

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  get "pages/home"
  get "pages/about"
  get "pages/contacts"

  root "pages#home"

  get "about", to: "pages#about"
  get "contacts", to: "pages#contacts"
  get "my-courses", to: "courses#my_courses"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "logout", to: "sessions#destroy"

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check

  # інші коментарі та маршрути
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Vx Academy2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <body>
  <header class="site-header">
    <div class="container">
      <a href="/" class="logo">VX Академія</a>
      <nav class="main-nav">
        <%= link_to 'Головна', root_path %>
        <%= link_to 'Курси', courses_path %>
        <%= link_to 'Мої курси', my_courses_path %>
        <%= link_to 'Про нас', about_path %>
      </nav>
      <% if logged_in? %>
        <%= link_to 'Профіль', user_path(current_user) if logged_in? %>
        Привіт, <%= current_user.name %>

        <%= link_to "Вийти", logout_path, method: :delete, data: { confirm: "Ви дійсно хочете вийти?" } %>
      <% else %>
        <%= link_to "Увійти", login_path %>
        <%= link_to "Зареєструватися", new_user_path %>
      <% end %>
    </div>
  </header>

  <main class="site-content">
    <%= yield %>
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>© <%= Time.now.year %> VX Академія | Всі права захищено.</p>
      <div class="social-links">
        <a href="#">Facebook</a>
        <a href="#">Instagram</a>
        <a href="#">YouTube</a>
      </div>
    </div>
  </footer>
</body>

</html>